# Generated by Django 4.2.2 on 2024-01-12 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('price_of_item', models.FloatField(default=0.0, max_length=2)),
                ('session_id', models.CharField(blank=True, default=0, max_length=120, null=True)),
                ('total', models.FloatField(default=0.0, max_length=2)),
                ('weight_in_grams', models.FloatField(blank=True, default=0.0, max_length=2, null=True)),
                ('meta_data', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0, max_length=2)),
                ('vat', models.FloatField(default=0.0, max_length=2)),
                ('shipping', models.FloatField(default=0.0, max_length=2)),
                ('subtotal', models.FloatField(default=0.0, max_length=2)),
                ('weight_in_grams', models.FloatField(blank=True, default=0.0, max_length=2, null=True)),
                ('meta_data', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(blank=True, default=None, to='carts.cartitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
