# Generated by Django 5.0.6 on 2025-04-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_shipping_alter_cart_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
