# Generated by Django 5.0.6 on 2025-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='weight_in_grams',
            field=models.FloatField(default=0.0, max_length=2),
        ),
    ]
