# Generated by Django 5.0.6 on 2025-04-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_weight_in_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_of_item',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='vat',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
    ]
