# Generated by Django 5.0.6 on 2025-04-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cartitem_price_of_item_alter_cartitem_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
        migrations.AlterField(
            model_name='cart',
            name='vat',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
    ]
