# Generated by Django 5.0.6 on 2025-04-06 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_tag_product_public_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(choices=[(Decimal('0.20'), 'Standard Rate 20%'), (Decimal('0.05'), 'Reduced Rate 5%'), (Decimal('0.00'), 'Zero Rate 0%')], default=0.0, max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
