# Generated by Django 5.0.6 on 2025-04-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_vat_rate_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
