# Generated by Django 5.0.6 on 2024-12-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_tag_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(choices=[(0.2, 'Standard rate'), (0.05, 'Reduced rate'), (0, 'Zero rate')], default=0.0, max_length=2),
        ),
    ]
