# Generated by Django 5.0.6 on 2025-04-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
    ]
