# Generated by Django 5.0.6 on 2024-12-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(choices=[(0.2, 'Standard rate'), (0.05, 'Reduced rate'), (0, 'Zero rate')], decimal_places=20, default=0, max_digits=20),
        ),
    ]
