# Generated by Django 5.0.6 on 2025-04-12 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(choices=[(Decimal('0.20'), 'Standard Rate 20%'), (Decimal('0.05'), 'Reduced Rate 5%'), (Decimal('0.00'), 'Zero Rate 0%')], default=0.0),
        ),
    ]
