# Generated by Django 5.0.6 on 2025-04-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(choices=[(0.2, 'Standard Rate 20%'), (0.05, 'Reduced Rate 5%'), (0.0, 'Zero Rate 0%')], default=0.0),
        ),
    ]
