# Generated by Django 5.0.6 on 2024-12-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price_alter_product_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(choices=[('Standard', 'Standard'), ('rate', 'Rate')], decimal_places=2, default=0, max_digits=10),
        ),
    ]
