# Generated by Django 5.0.6 on 2025-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=28, default=0.0, max_digits=33),
        ),
    ]
