# Generated by Django 5.0.6 on 2024-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(choices=[('0.2', 'Standard Rate 20%'), ('0.05', 'Reduced Rate 5%'), ('0.0', 'Zero Rate 0%')], decimal_places=2, max_digits=10),
        ),
    ]
