# Generated by Django 5.0.6 on 2024-12-05 17:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(choices=[(Decimal('0.299999999999999988897769753748434595763683319091796875'), 'Standard Rate 20%'), (Decimal('0.05000000000000000277555756156289135105907917022705078125'), 'Reduced Rate 5%'), (Decimal('0'), 'Zero Rate 0%')], decimal_places=3, max_digits=10),
        ),
    ]
