# Generated by Django 5.0.6 on 2024-12-20 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(default=0.0, max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(choices=[(Decimal('0.20'), 'Standard Rate 20%'), (Decimal('0.05'), 'Reduced Rate 5%'), (Decimal('0.00'), 'Zero Rate 0%')], default=0.0, max_length=2),
        ),
    ]
