# Generated by Django 5.0.6 on 2025-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=28, max_digits=33),
        ),
    ]
