# Generated by Django 5.0.6 on 2025-04-19 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
