# Generated by Django 5.0.6 on 2024-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blurb',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
