# Generated by Django 5.0.6 on 2025-04-19 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_timestamp_alter_order_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
